apiVersion: v1
baseDomain: npss.lab
metadata:
  name: abc
networking:
  machineCIDR: 192.168.122.0/24
  networkType: OVNKubernetes
compute:
- name: worker
  replicas: 2 
controlPlane:
  name: master
  replicas: 3
  platform:
    baremetal: {}
platform:
  baremetal:
    apiVIP: 192.168.122.254
    ingressVIP: 192.168.122.254
    provisioningNetwork: Managed
    provisioningNetworkCIDR: 172.16.1.0/24
    provisioningNetworkInterface: enp2s0
    hosts:
      - name: openshift-master-0
        role: master
        bmc:
          address: ipmi://10
          username: 
          password: 
          disableCertificateVerification: true
        bootMACAddress: F8:
        rootDeviceHints:
         deviceName: "/dev/sda"
      - name: openshift-master-1
        role: master
       bmc:
          address: ipmi://10
          username: 
          password: 
          disableCertificateVerification: true
        bootMACAddress: F8:
        rootDeviceHints:
         deviceName: "/dev/sda"
      - name: openshift-master-2
        role: master
        bmc:
          address: ipmi://10
          username: 
          password: 
          disableCertificateVerification: true
        bootMACAddress: F8:
        rootDeviceHints:
         deviceName: "/dev/sda"
      - name: openshift-worker-0
        role: worker
        bmc:
          address: ipmi://10
          username: 
          password: 
          disableCertificateVerification: true
        bootMACAddress: F8:
        rootDeviceHints:
         deviceName: "/dev/sda"
      - name: openshift-worker-1
        role: worker
        bmc:
          address: ipmi://10
          username: 
          password: 
          disableCertificateVerification: true
        bootMACAddress: F8:
        rootDeviceHints:
         deviceName: "/dev/sda"
pullSecret: ''
sshKey: ''
